// PMP Vocabulary Data
// Nguồn: 12 module tài liệu Mentora/VTI (PMP07.2601) + bổ sung PMBOK7 Glossary / PMI Lexicon,
// công thức EVM & Risk phổ biến trong đề thi PMP.

const MODULES = [
  { id: 1, name: "Nhập môn PMP & Kỳ thi", short: "Intro" },
  { id: 2, name: "Nền tảng Quản lý Dự án", short: "Fundamentals" },
  { id: 3, name: "Stakeholder & Communication", short: "Stakeholder" },
  { id: 4, name: "Resource & Team", short: "Resource" },
  { id: 5, name: "Scope Management", short: "Scope" },
  { id: 6, name: "Schedule Management", short: "Schedule" },
  { id: 7, name: "Agile & Scrum", short: "Agile" },
  { id: 8, name: "Adaptive Planning & Value Delivery", short: "Adaptive" },
  { id: 9, name: "Financial Management", short: "Financial" },
  { id: 10, name: "Quality Management", short: "Quality" },
  { id: 11, name: "Risk Management", short: "Risk" },
  { id: 12, name: "Procurement Management", short: "Procurement" },
];

const VOCAB = [
  // ===== MODULE 1: Nhập môn PMP & Kỳ thi =====
  { id: "m1-01", m: 1, term: "PMI (Project Management Institute)", vi: "Tổ chức phi lợi nhuận toàn cầu, đơn vị \"sáng tạo\" ra chứng chỉ PMP; thành lập năm 1969, có 300+ chi hội, 700.000+ hội viên." },
  { id: "m1-02", m: 1, term: "PMP (Project Management Professional)", vi: "Chứng chỉ hành nghề quản lý dự án do PMI cấp (1984), được công nhận tại hơn 200 quốc gia, hơn 1,5 triệu người sở hữu." },
  { id: "m1-03", m: 1, term: "PMBOK Guide", vi: "\"Bộ công cụ\" tham khảo tiêu chuẩn của PMI (A Guide to the Project Management Body of Knowledge); không phải nội dung trực tiếp ra đề mà chỉ là tài liệu tham khảo." },
  { id: "m1-04", m: 1, term: "ECO (Exam Content Outline)", vi: "\"Bản thiết kế\" chính thức quy định nội dung đề thi PMP, chia thành 3 domain, mỗi domain gồm nhiều task và enabler." },
  { id: "m1-05", m: 1, term: "Domain", vi: "Cấp cao nhất trong ECO, thể hiện lĩnh vực kiến thức cốt lõi cần thiết cho hành nghề (People, Process, Business Environment)." },
  { id: "m1-06", m: 1, term: "Task", vi: "Trách nhiệm cụ thể của PM trong một domain — trả lời câu hỏi \"phải làm gì\"." },
  { id: "m1-07", m: 1, term: "Enabler", vi: "Ví dụ minh họa hành động cụ thể để hoàn thành một task; đây là nơi các câu hỏi tình huống trong đề thi được xây dựng." },
  { id: "m1-08", m: 1, term: "Domain I – People (33%, 59 câu)", vi: "Domain về yếu tố con người: quản lý xung đột, dẫn dắt đội nhóm, gắn kết stakeholder, đảm bảo chuyển giao kiến thức." },
  { id: "m1-09", m: 1, term: "Domain II – Process (41%, 74 câu)", vi: "Domain về cơ chế triển khai giá trị và quản lý ràng buộc: lập kế hoạch tích hợp, tối ưu chất lượng, quản lý ràng buộc dự án." },
  { id: "m1-10", m: 1, term: "Domain III – Business Environment (26%, 47 câu)", vi: "Domain đánh giá yếu tố bên ngoài và thay đổi tổ chức: quản trị dự án, tuân thủ, đánh giá thay đổi bên ngoài, hỗ trợ chuyển đổi tổ chức." },
  { id: "m1-11", m: 1, term: "Predictive approach (Waterfall)", vi: "Cách tiếp cận dự đoán/thác nước: lập kế hoạch chi tiết ngay từ đầu, thực hiện tuần tự; chiếm ~40% đề thi." },
  { id: "m1-12", m: 1, term: "Adaptive approach (Agile)", vi: "Cách tiếp cận thích ứng/linh hoạt: giao hàng lặp đi lặp lại, phản hồi liên tục; cùng Hybrid chiếm ~60% đề thi." },
  { id: "m1-13", m: 1, term: "Hybrid approach", vi: "Kết hợp giữa predictive và adaptive tùy theo nhu cầu và bối cảnh của từng phần dự án." },
  { id: "m1-14", m: 1, term: "Project", vi: "Nỗ lực tạm thời được thực hiện để tạo ra một sản phẩm, dịch vụ hoặc kết quả duy nhất." },
  { id: "m1-15", m: 1, term: "Program", vi: "Nhóm các dự án, chương trình con và hoạt động liên quan được quản lý phối hợp để đạt lợi ích mà nếu quản lý riêng lẻ sẽ không đạt được." },
  { id: "m1-16", m: 1, term: "Portfolio", vi: "Tập hợp các dự án, chương trình, portfolio con và hoạt động vận hành được quản lý theo nhóm để đạt mục tiêu chiến lược của tổ chức." },
  { id: "m1-17", m: 1, term: "Operations", vi: "Hoạt động vận hành lặp đi lặp lại, liên tục — khác với dự án vốn có tính tạm thời và tạo ra kết quả duy nhất." },
  { id: "m1-18", m: 1, term: "Project Management", vi: "Việc áp dụng kiến thức, kỹ năng, công cụ và kỹ thuật vào các hoạt động của dự án để đáp ứng yêu cầu của dự án." },
  { id: "m1-19", m: 1, term: "Tailoring", vi: "Việc điều chỉnh phương pháp/quy trình quản lý dự án chuẩn cho phù hợp bối cảnh cụ thể — \"không có công thức chung cho mọi dự án\"." },
  { id: "m1-20", m: 1, term: "Servant Leadership", vi: "Phong cách lãnh đạo phục vụ: đặt nhu cầu của đội nhóm lên trước, hỗ trợ họ có nguồn lực và môi trường làm việc tốt nhất." },
  { id: "m1-21", m: 1, term: "CBT (Computer-Based Testing)", vi: "Hình thức thi PMP tại trung tâm khảo thí, làm bài trên máy tính." },
  { id: "m1-22", m: 1, term: "OPT (Online Proctored Testing)", vi: "Hình thức thi PMP trực tuyến, có giám sát từ xa qua camera." },
  { id: "m1-23", m: 1, term: "PMI-recognized education (35 contact hours)", vi: "Yêu cầu 35 giờ đào tạo quản lý dự án được PMI công nhận — một trong 3 điều kiện bắt buộc để đăng ký thi PMP." },

  // ===== MODULE 2: Nền tảng Quản lý Dự án =====
  { id: "m2-01", m: 2, term: "Project Life Cycle", vi: "Chuỗi các giai đoạn (phase) mà một dự án trải qua từ khi khởi tạo đến khi kết thúc." },
  { id: "m2-02", m: 2, term: "Project Phase", vi: "Tập hợp các hoạt động dự án có liên quan logic với nhau, kết thúc bằng việc hoàn thành một hoặc nhiều deliverable." },
  { id: "m2-03", m: 2, term: "Phase Gate (Stage Gate)", vi: "Điểm review ở cuối một giai đoạn để quyết định: tiếp tục, tiếp tục có điều chỉnh, hay kết thúc dự án/chương trình." },
  { id: "m2-04", m: 2, term: "Predictive Life Cycle", vi: "Vòng đời dự đoán: lập kế hoạch chi tiết toàn bộ dự án ngay từ đầu, tiến hành tuần tự kiểu thác nước." },
  { id: "m2-05", m: 2, term: "Iterative Life Cycle", vi: "Vòng đời lặp: sản phẩm được phát triển qua nhiều vòng lặp, mỗi vòng bổ sung và tinh chỉnh thêm." },
  { id: "m2-06", m: 2, term: "Incremental Life Cycle", vi: "Vòng đời tăng dần: sản phẩm được xây dựng và bàn giao từng phần có thể dùng ngay." },
  { id: "m2-07", m: 2, term: "Adaptive (Agile) Life Cycle", vi: "Vòng đời thích ứng: kết hợp lặp và tăng dần, phản hồi nhanh với thay đổi." },
  { id: "m2-08", m: 2, term: "Product Life Cycle", vi: "Chuỗi giai đoạn thể hiện sự tiến hóa của một sản phẩm, từ ý tưởng, tăng trưởng, trưởng thành đến khi ngừng sản xuất — khác với vòng đời dự án." },
  { id: "m2-09", m: 2, term: "Stacey Complexity Matrix", vi: "Ma trận đánh giá độ phức tạp dự án dựa trên độ rõ ràng của yêu cầu (what) và cách làm/công nghệ (how): Simple, Complicated, Complex, Anarchy (Chaotic)." },
  { id: "m2-10", m: 2, term: "Performance Domain", vi: "Nhóm hoạt động liên quan cần thiết để triển khai dự án hiệu quả: Governance, Stakeholder, Scope, Resource/Team, Schedule, Finance, Risk..." },
  { id: "m2-11", m: 2, term: "Organizational Structure", vi: "Cấu trúc tổ chức ảnh hưởng đến quyền hạn của PM: Functional, Weak/Balanced/Strong Matrix, Projectized, Composite." },
  { id: "m2-12", m: 2, term: "Functional Organization", vi: "Cấu trúc tổ chức theo chức năng; PM có quyền hạn rất thấp hoặc gần như không có." },
  { id: "m2-13", m: 2, term: "Projectized Organization", vi: "Cấu trúc tổ chức theo dự án; PM có quyền hạn cao nhất, nhân sự báo cáo trực tiếp cho PM." },
  { id: "m2-14", m: 2, term: "Matrix Organization (Weak/Balanced/Strong)", vi: "Cấu trúc ma trận kết hợp chức năng và dự án; quyền hạn PM tăng dần từ Weak đến Strong." },
  { id: "m2-15", m: 2, term: "Project Management Office (PMO)", vi: "Đơn vị chuẩn hóa các quy trình quản trị dự án và hỗ trợ chia sẻ nguồn lực, phương pháp, công cụ." },
  { id: "m2-16", m: 2, term: "Supportive PMO", vi: "PMO hỗ trợ: cung cấp template, best practice, đào tạo — mức độ kiểm soát thấp." },
  { id: "m2-17", m: 2, term: "Controlling PMO", vi: "PMO kiểm soát: yêu cầu tuân thủ khuôn mẫu và quy trình quản trị — mức độ kiểm soát trung bình." },
  { id: "m2-18", m: 2, term: "Directive PMO", vi: "PMO chỉ đạo trực tiếp: PM báo cáo và chịu sự quản lý trực tiếp của PMO — mức độ kiểm soát cao." },
  { id: "m2-19", m: 2, term: "Enterprise Environmental Factors (EEF)", vi: "Yếu tố môi trường doanh nghiệp (nội bộ/bên ngoài) ảnh hưởng đến dự án nhưng nằm ngoài tầm kiểm soát của đội dự án." },
  { id: "m2-20", m: 2, term: "Organizational Process Assets (OPA)", vi: "Tài sản quy trình của tổ chức: chính sách, quy trình, thủ tục, kho kiến thức lịch sử mà đội dự án có thể sử dụng." },
  { id: "m2-21", m: 2, term: "Project Governance", vi: "Khung, chức năng và quy trình hướng dẫn các hoạt động và quyết định quản lý dự án nhằm tối ưu hóa giá trị mang lại." },
  { id: "m2-22", m: 2, term: "PMIS (Project Management Information System)", vi: "Hệ thống thông tin quản lý dự án dùng để thu thập, tích hợp và phổ biến kết quả đầu ra của các quy trình quản lý dự án." },
  { id: "m2-23", m: 2, term: "Work Authorization System", vi: "Hệ thống ủy quyền công việc, quy định cách công việc được phép thực hiện, bởi ai, đúng lúc, đúng trình tự." },
  { id: "m2-24", m: 2, term: "Configuration Management System", vi: "Hệ thống quản lý cấu hình, tập trung vào đặc tả kỹ thuật của deliverable và của các quy trình." },
  { id: "m2-25", m: 2, term: "Change Control System", vi: "Hệ thống kiểm soát thay đổi, tập trung vào việc xác định, ghi nhận và kiểm soát thay đổi đối với dự án và baseline." },
  { id: "m2-26", m: 2, term: "Corrective Action", vi: "Hành động khắc phục nhằm đưa hiệu suất dự án về đúng với kế hoạch quản lý dự án." },
  { id: "m2-27", m: 2, term: "Preventive Action", vi: "Hành động phòng ngừa nhằm giảm khả năng xảy ra hậu quả tiêu cực tiềm ẩn." },
  { id: "m2-28", m: 2, term: "Defect Repair", vi: "Yêu cầu sửa chữa lỗi sản phẩm được phát hiện qua quy trình chất lượng." },
  { id: "m2-29", m: 2, term: "Human-in-the-Loop (HITL)", vi: "Nguyên tắc đảm bảo con người luôn là người ra quyết định cuối cùng khi ứng dụng AI trong quản lý dự án, không phải thuật toán." },
  { id: "m2-30", m: 2, term: "Assumption Log", vi: "Nhật ký giả định: tài liệu ghi lại các giả định và ràng buộc của dự án trong suốt vòng đời, được cập nhật liên tục khi có thông tin mới." },
  { id: "m2-31", m: 2, term: "Lessons Learned Register", vi: "Sổ ghi nhận bài học kinh nghiệm: tài liệu tích lũy kiến thức trong suốt dự án, dùng để cải thiện dự án hiện tại và các dự án tương lai." },
  { id: "m2-32", m: 2, term: "Organizational Change Management (OCM)", vi: "Quản lý thay đổi tổ chức: cách tiếp cận có cấu trúc để chuyển đổi cá nhân, đội nhóm và tổ chức từ trạng thái hiện tại sang trạng thái mong muốn — thuộc Domain III (Business Environment)." },
  { id: "m2-33", m: 2, term: "ADKAR Model", vi: "Mô hình quản lý thay đổi ở cấp cá nhân: Awareness, Desire, Knowledge, Ability, Reinforcement." },
  { id: "m2-34", m: 2, term: "Benefits Management Plan", vi: "Kế hoạch quản lý lợi ích: mô tả lợi ích của dự án sẽ được tạo ra, tối đa hóa và đo lường như thế nào, khi nào." },
  { id: "m2-35", m: 2, term: "Compliance", vi: "Tuân thủ: đảm bảo dự án đáp ứng luật pháp, quy định, tiêu chuẩn ngành và chính sách nội bộ liên quan — một task trọng tâm của Domain III." },
  { id: "m2-36", m: 2, term: "Project Management Plan", vi: "Kế hoạch quản lý dự án: tài liệu trung tâm mô tả cách dự án sẽ được thực thi, giám sát/kiểm soát và kết thúc; tổng hợp tất cả các kế hoạch phụ (scope, schedule, cost, risk, quality...)." },
  { id: "m2-37", m: 2, term: "Deliverable", vi: "Sản phẩm bàn giao: bất kỳ sản phẩm, kết quả hoặc khả năng cung cấp dịch vụ nào là duy nhất và có thể kiểm chứng được, cần tạo ra để hoàn thành một quy trình, giai đoạn hoặc dự án." },
  { id: "m2-38", m: 2, term: "Change Request", vi: "Yêu cầu thay đổi: đề xuất chính thức nhằm sửa đổi một tài liệu, deliverable hoặc baseline của dự án; là đầu vào cho quy trình Perform Integrated Change Control." },
  { id: "m2-39", m: 2, term: "Project Manager", vi: "Người được tổ chức thực hiện bổ nhiệm để dẫn dắt đội ngũ chịu trách nhiệm đạt được mục tiêu dự án." },
  { id: "m2-40", m: 2, term: "Progressive Elaboration", vi: "Chi tiết hóa dần: quá trình lặp đi lặp lại, tăng dần mức độ chi tiết của kế hoạch quản lý dự án khi có thêm thông tin và ước lượng chính xác hơn — nền tảng của Rolling Wave Planning." },
  { id: "m2-41", m: 2, term: "Key Performance Indicator (KPI)", vi: "Chỉ số hiệu suất chính: thước đo do lãnh đạo tổ chức xác định để đánh giá mức độ đạt được mục tiêu chiến lược." },
  { id: "m2-42", m: 2, term: "Kickoff Meeting", vi: "Cuộc họp khởi động: buổi gặp mặt đội dự án và các stakeholder chính vào đầu dự án nhằm thiết lập kỳ vọng chung và chính thức bắt đầu công việc." },
  { id: "m2-43", m: 2, term: "Steering Committee", vi: "Ban chỉ đạo: nhóm các stakeholder cấp cao đưa ra định hướng, hỗ trợ cho dự án và ra quyết định vượt quá thẩm quyền của đội dự án." },
  { id: "m2-44", m: 2, term: "Go/No-Go Decision", vi: "Quyết định tiếp tục hay dừng: xác định một sáng kiến/dự án nên tiếp tục hay bị dừng lại, thường được đưa ra tại các phase gate." },
  { id: "m2-45", m: 2, term: "Sustainability", vi: "Tính bền vững: thực hành mang lại kết quả theo cách có thể duy trì lâu dài, cân bằng giữa năng suất với con người, tài nguyên và môi trường — khái niệm ngày càng được nhấn mạnh trong Domain III." },
  { id: "m2-46", m: 2, term: "Business Objective", vi: "Mục tiêu kinh doanh: đại diện có thể đo lường được cho những gì tổ chức muốn đạt được; phải cụ thể và gắn kết với mục tiêu chiến lược của tổ chức." },
  { id: "m2-47", m: 2, term: "Benefits Realization Plan", vi: "Kế hoạch hiện thực hóa lợi ích: tài liệu nêu các hoạt động cần thiết để đạt được lợi ích đã hoạch định, kèm mốc thời gian và nguồn lực cần thiết." },
  { id: "m2-48", m: 2, term: "Change Management Plan", vi: "Kế hoạch quản lý thay đổi: thành phần của kế hoạch quản lý dự án thiết lập change control board, phạm vi thẩm quyền của nó, và cách hệ thống kiểm soát thay đổi sẽ được triển khai." },
  { id: "m2-49", m: 2, term: "Objectives and Key Results (OKRs)", vi: "Khung thiết lập mục tiêu dùng để xác định và theo dõi mục tiêu (Objectives) cùng kết quả then chốt (Key Results); giúp gắn kết mục tiêu cá nhân, đội nhóm và tổ chức." },

  // ===== MODULE 3: Stakeholder & Communication =====
  { id: "m3-01", m: 3, term: "Stakeholder", vi: "Cá nhân, nhóm hoặc tổ chức có thể ảnh hưởng, bị ảnh hưởng, hoặc tự cảm thấy bị ảnh hưởng bởi quyết định, hoạt động hay kết quả của dự án." },
  { id: "m3-02", m: 3, term: "Business Case", vi: "Nghiên cứu khả thi kinh tế dùng để xác thực lợi ích của một dự án, là cơ sở phê duyệt các hoạt động quản lý dự án tiếp theo." },
  { id: "m3-03", m: 3, term: "Project Charter", vi: "Văn kiện chính thức công nhận sự tồn tại của dự án, trao quyền cho PM sử dụng nguồn lực tổ chức; dự án chưa chính thức tồn tại nếu chưa có charter." },
  { id: "m3-04", m: 3, term: "Project Sponsor", vi: "Người/nhóm cung cấp nguồn lực, hỗ trợ và bảo trợ chính trị cho dự án, cùng PM khởi tạo project charter." },
  { id: "m3-05", m: 3, term: "Power/Interest Grid", vi: "Ma trận phân loại stakeholder theo hai trục: mức độ quyền lực (power) và mức độ quan tâm (interest)." },
  { id: "m3-06", m: 3, term: "Stakeholder Register", vi: "Tài liệu ghi nhận thông tin nhận diện, đánh giá và phân loại các stakeholder của dự án." },
  { id: "m3-07", m: 3, term: "Stakeholder Engagement Assessment Matrix", vi: "Ma trận so sánh mức độ gắn kết hiện tại (C) và mong muốn (D) của từng stakeholder: Unaware, Resistant, Neutral, Supportive, Leading." },
  { id: "m3-08", m: 3, term: "Communication", vi: "Việc trao đổi thông tin (chủ ý hoặc không chủ ý) dưới dạng ý tưởng, chỉ dẫn hoặc cảm xúc; PM dành 75-90% thời gian để giao tiếp." },
  { id: "m3-09", m: 3, term: "Push Communication", vi: "Giao tiếp \"đẩy\": gửi thông tin cụ thể đến người nhận cụ thể (email, thư); không đảm bảo người nhận đã đọc/hiểu." },
  { id: "m3-10", m: 3, term: "Pull Communication", vi: "Giao tiếp \"kéo\": thông tin khối lượng lớn cho nhiều người, người nhận tự truy cập khi cần (website, database)." },
  { id: "m3-11", m: 3, term: "Interactive Communication", vi: "Giao tiếp tương tác hai chiều theo thời gian thực (họp, gọi điện) — hình thức hiệu quả nhất." },
  { id: "m3-12", m: 3, term: "Communication Channels Formula", vi: "Công thức tính số kênh giao tiếp: N(N-1)/2, với N là số lượng stakeholder." },
  { id: "m3-13", m: 3, term: "Ground Rules", vi: "Quy tắc ứng xử mà đội nhóm và stakeholder cùng thống nhất tuân theo để giảm xung đột." },
  { id: "m3-14", m: 3, term: "Active Listening", vi: "Kỹ năng lắng nghe chủ động: lắng nghe để hiểu chứ không phải để phản hồi." },
  { id: "m3-15", m: 3, term: "Issue Log", vi: "Nhật ký vấn đề: ghi nhận vấn đề, mức độ ưu tiên, người phụ trách và hạn xử lý." },
  { id: "m3-16", m: 3, term: "Change Log", vi: "Nhật ký thay đổi: theo dõi tiến trình của từng thay đổi (được duyệt, từ chối hay hoãn lại)." },
  { id: "m3-17", m: 3, term: "Conflict Resolution Modes", vi: "5 chế độ giải quyết xung đột: Collaborate/Problem-solve (win-win), Force/Direct (win-lose), Compromise (lose-lose một phần), Smooth/Accommodate, Withdraw/Avoid." },
  { id: "m3-18", m: 3, term: "5 Cs of Written Communication", vi: "Nguyên tắc viết hiệu quả: Clear, Concise, Correct, Coherent, Controlling." },
  { id: "m3-19", m: 3, term: "Status Report", vi: "Báo cáo tình trạng dự án tại một thời điểm cụ thể (snapshot hiện tại)." },
  { id: "m3-20", m: 3, term: "Progress Report", vi: "Báo cáo tiến độ, mô tả những gì đã hoàn thành trong một khoảng thời gian đã qua." },
  { id: "m3-21", m: 3, term: "Variance Report", vi: "Báo cáo sai lệch: so sánh thực tế với kế hoạch (baseline) để phát hiện chênh lệch." },
  { id: "m3-22", m: 3, term: "Trend Report", vi: "Báo cáo xu hướng: so sánh kết quả qua nhiều kỳ để xem hiệu suất cải thiện hay suy giảm." },
  { id: "m3-23", m: 3, term: "Forecast Report", vi: "Báo cáo dự báo: dự đoán tình trạng dự án trong tương lai dựa trên dữ liệu và xu hướng hiện tại." },
  { id: "m3-24", m: 3, term: "S.M.A.R.T Objectives", vi: "Mục tiêu dự án cần cụ thể, đo lường được, khả thi, liên quan và có thời hạn (Specific, Measurable, Achievable, Relevant, Time-bound)." },
  { id: "m3-25", m: 3, term: "Benefit Cost Ratio (BCR)", vi: "Tỷ lệ lợi ích trên chi phí, dùng trong phân tích lựa chọn dự án; BCR > 1 nghĩa là lợi ích lớn hơn chi phí." },
  { id: "m3-26", m: 3, term: "Net Present Value (NPV)", vi: "Giá trị hiện tại ròng của dòng tiền dự án; NPV dương nghĩa là dự án sinh lời, nên ưu tiên dự án có NPV lớn hơn." },
  { id: "m3-27", m: 3, term: "Internal Rate of Return (IRR)", vi: "Tỷ suất hoàn vốn nội bộ; IRR càng cao thì dự án càng hấp dẫn về tài chính." },
  { id: "m3-28", m: 3, term: "Sunk Cost", vi: "Chi phí chìm: chi phí đã bỏ ra và không thể thu hồi, không nên ảnh hưởng đến quyết định trong tương lai." },
  { id: "m3-29", m: 3, term: "Salience Model", vi: "Mô hình phân loại stakeholder theo 3 yếu tố: Power (quyền lực), Urgency (tính cấp bách), Legitimacy (tính chính danh)." },
  { id: "m3-30", m: 3, term: "Directions of Influence", vi: "Hướng ảnh hưởng của stakeholder: Upward (cấp trên), Downward (cấp dưới), Outward (bên ngoài dự án), Sideward (ngang hàng, cùng cấp PM)." },
  { id: "m3-31", m: 3, term: "Business Value", vi: "Giá trị kinh doanh: lợi ích ròng (có thể định lượng hoặc không) mà một dự án/hoạt động mang lại cho tổ chức, vượt trên chi phí bỏ ra." },
  { id: "m3-32", m: 3, term: "Feasibility Analysis", vi: "Phân tích khả thi: nghiên cứu đánh giá tính khả thi của dự án trên nhiều khía cạnh (vận hành, công nghệ, chi phí, thời gian) trước khi quyết định đầu tư." },
  { id: "m3-33", m: 3, term: "Stakeholder Engagement Plan", vi: "Kế hoạch gắn kết stakeholder: thành phần của kế hoạch quản lý dự án xác định chiến lược và hành động cần thiết để thúc đẩy sự tham gia hiệu quả của các stakeholder." },
  { id: "m3-34", m: 3, term: "Communications Management Plan", vi: "Kế hoạch quản lý truyền thông: thành phần của kế hoạch quản lý dự án mô tả cách thức, thời điểm và người chịu trách nhiệm quản lý, phổ biến thông tin dự án." },
  { id: "m3-35", m: 3, term: "Disbenefit", vi: "Kết quả tiêu cực: hệ quả đo lường được từ một outcome mà một hoặc nhiều stakeholder cho là bất lợi — cần được xác định và quản lý tương tự như benefit." },

  // ===== MODULE 4: Resource & Team =====
  { id: "m4-01", m: 4, term: "RACI Chart (RAM)", vi: "Ma trận phân công trách nhiệm: Responsible (người thực hiện), Accountable (người chịu trách nhiệm cuối cùng), Consulted (được tham vấn), Informed (được thông báo)." },
  { id: "m4-02", m: 4, term: "Resource Breakdown Structure (RBS)", vi: "Cấu trúc phân cấp nguồn lực theo loại và danh mục nguồn lực." },
  { id: "m4-03", m: 4, term: "Team Charter", vi: "Điều lệ đội nhóm, thiết lập kỳ vọng rõ ràng về hành vi được chấp nhận của các thành viên." },
  { id: "m4-04", m: 4, term: "Theory X", vi: "Thuyết X: cho rằng con người vốn lười biếng, cần bị giám sát và kiểm soát chặt chẽ (phong cách quản lý độc đoán)." },
  { id: "m4-05", m: 4, term: "Theory Y", vi: "Thuyết Y: cho rằng con người tự giác, có trách nhiệm và thích làm việc không cần giám sát (phong cách laissez-faire)." },
  { id: "m4-06", m: 4, term: "Theory Z", vi: "Thuyết Z (kiểu Nhật Bản): tập trung xây dựng lòng trung thành lâu dài của nhân viên qua công việc ổn định trọn đời." },
  { id: "m4-07", m: 4, term: "Maslow's Hierarchy of Needs", vi: "Tháp nhu cầu Maslow: hành vi con người được thúc đẩy theo thứ tự từ nhu cầu cơ bản đến tự hoàn thiện bản thân." },
  { id: "m4-08", m: 4, term: "Herzberg's Two-Factor Theory", vi: "Thuyết hai yếu tố của Herzberg: yếu tố động lực (tạo sự hài lòng) và yếu tố duy trì (không tạo động lực nhưng gây bất mãn nếu thiếu)." },
  { id: "m4-09", m: 4, term: "McClelland's Theory of Needs", vi: "Thuyết nhu cầu của McClelland: 3 nhu cầu chính thúc đẩy con người — Achievement (thành tựu), Affiliation (liên kết), Power (quyền lực)." },
  { id: "m4-10", m: 4, term: "Situational Leadership (Hersey-Blanchard)", vi: "Mô hình lãnh đạo tình huống với 4 phong cách: Directing, Coaching, Supporting, Delegating, tùy mức độ trưởng thành của đội nhóm." },
  { id: "m4-11", m: 4, term: "Halo Effect", vi: "Hiệu ứng hào quang: giả định một người giỏi ở lĩnh vực này sẽ giỏi ở lĩnh vực khác (VD: lập trình viên giỏi ắt sẽ là PM giỏi) — cần tránh." },
  { id: "m4-12", m: 4, term: "Co-located Team", vi: "Đội nhóm làm việc cùng một địa điểm vật lý để tăng cường giao tiếp và tinh thần đồng đội." },
  { id: "m4-13", m: 4, term: "Virtual Team", vi: "Đội nhóm ảo, làm việc từ xa và giao tiếp chủ yếu qua công nghệ điện tử." },
  { id: "m4-14", m: 4, term: "Distributed Team", vi: "Đội nhóm phân tán, có ít nhất một thành viên làm việc off-site." },
  { id: "m4-15", m: 4, term: "War Room", vi: "\"Phòng chiến tranh\": phòng họp trang bị công cụ giao tiếp điện tử để tăng cường phối hợp cho đội co-located." },
  { id: "m4-16", m: 4, term: "Emotional Intelligence (EQ)", vi: "Trí tuệ cảm xúc: khả năng nhận biết, kiểm soát và thể hiện cảm xúc của bản thân, đồng thời xử lý mối quan hệ khéo léo." },
  { id: "m4-17", m: 4, term: "Forms of Power", vi: "Các hình thức quyền lực của PM: Expert (chuyên môn), Reward (khen thưởng), Referent (uy tín cá nhân), Legitimate/Position (chức vụ), Coercive (cưỡng ép) — Expert và Reward hiệu quả nhất." },
  { id: "m4-18", m: 4, term: "Six Thinking Hats", vi: "Kỹ thuật 6 chiếc mũ tư duy của Edward de Bono, mỗi màu đại diện một góc nhìn: Blue (tổng quan), White (dữ kiện), Red (cảm xúc), Black (tiêu cực), Yellow (tích cực), Green (sáng tạo)." },
  { id: "m4-19", m: 4, term: "Multi-Criteria Decision Analysis (MCDA)", vi: "Phân tích quyết định đa tiêu chí: đánh giá các lựa chọn dựa trên nhiều tiêu chí khác nhau để chọn phương án tốt nhất." },
  { id: "m4-20", m: 4, term: "Analogous Estimating", vi: "Ước lượng tương tự: dựa trên dữ liệu của dự án tương tự trong quá khứ; nhanh nhưng độ chính xác thấp." },
  { id: "m4-21", m: 4, term: "Parametric Estimating", vi: "Ước lượng tham số: sử dụng mối quan hệ thống kê giữa dữ liệu lịch sử và biến số để tính toán." },
  { id: "m4-22", m: 4, term: "Bottom-up Estimating", vi: "Ước lượng từ dưới lên: ước lượng chi tiết ở cấp hoạt động rồi tổng hợp lên; độ chính xác cao nhất." },
  { id: "m4-23", m: 4, term: "Resource Calendar", vi: "Lịch nguồn lực, xác định thời gian và thời lượng nguồn lực sẵn sàng cho dự án." },
  { id: "m4-24", m: 4, term: "Team vs Group", vi: "Team có tầm nhìn chung và mức phụ thuộc lẫn nhau cao; Group chỉ có lợi ích chung, làm việc độc lập." },
  { id: "m4-25", m: 4, term: "Tuckman's Stages of Team Development", vi: "5 giai đoạn phát triển đội nhóm theo mô hình Tuckman: Forming, Storming, Norming, Performing, Adjourning." },
  { id: "m4-26", m: 4, term: "Forming", vi: "Giai đoạn hình thành: các thành viên mới gặp nhau, còn dè dặt, lịch sự, chưa rõ vai trò của nhau." },
  { id: "m4-27", m: 4, term: "Storming", vi: "Giai đoạn xung đột: các thành viên bắt đầu va chạm quan điểm, cạnh tranh vai trò và cách làm việc." },
  { id: "m4-28", m: 4, term: "Norming", vi: "Giai đoạn ổn định: đội bắt đầu tin tưởng nhau, thiết lập quy tắc chung và làm việc phối hợp hơn." },
  { id: "m4-29", m: 4, term: "Performing", vi: "Giai đoạn hiệu suất cao: đội hoạt động trơn tru, tự tổ chức tốt, đạt hiệu quả cao nhất." },
  { id: "m4-30", m: 4, term: "Adjourning", vi: "Giai đoạn kết thúc (còn gọi là Mourning): đội giải tán sau khi hoàn thành mục tiêu công việc." },
  { id: "m4-31", m: 4, term: "Negotiation (Acquire Resource)", vi: "Đàm phán để đảm bảo nguồn lực: PM thương lượng với functional manager hoặc PM khác để có được nhân sự/nguồn lực khan hiếm cần thiết." },
  { id: "m4-32", m: 4, term: "Psychological Safety", vi: "An toàn tâm lý: niềm tin chung trong đội rằng các thành viên sẽ được chấp nhận, có thể lên tiếng, chấp nhận rủi ro và bày tỏ ý kiến mà không sợ hậu quả tiêu cực." },
  { id: "m4-33", m: 4, term: "Organizational Breakdown Structure (OBS)", vi: "Cấu trúc phân cấp tổ chức: biểu diễn phân cấp thể hiện mối quan hệ giữa các hoạt động dự án và các đơn vị tổ chức thực hiện chúng — song song với RBS và WBS." },

  // ===== MODULE 5: Scope Management =====
  { id: "m5-01", m: 5, term: "Requirement", vi: "Yêu cầu: điều kiện hoặc khả năng cần có ở sản phẩm/dịch vụ/kết quả để thỏa mãn một thỏa thuận hoặc đặc tả chính thức." },
  { id: "m5-02", m: 5, term: "Project Scope vs Product Scope", vi: "Phạm vi dự án (đo bằng project management plan) khác với phạm vi sản phẩm (đo bằng yêu cầu sản phẩm)." },
  { id: "m5-03", m: 5, term: "Scope Creep", vi: "Phình phạm vi: bổ sung tính năng/công việc không qua kiểm soát thay đổi chính thức, thường xuất phát từ phía khách hàng." },
  { id: "m5-04", m: 5, term: "Gold Plating", vi: "Mạ vàng: đội dự án tự ý thêm tính năng ngoài phạm vi (với ý tốt) nhưng không được yêu cầu — cũng cần tránh vì tốn nguồn lực và rủi ro." },
  { id: "m5-05", m: 5, term: "Scope Management Plan", vi: "Kế hoạch quản lý phạm vi: mô tả cách phạm vi sẽ được định nghĩa, phát triển, giám sát, kiểm soát và xác nhận." },
  { id: "m5-06", m: 5, term: "Requirements Traceability Matrix (RTM)", vi: "Ma trận truy xuất nguồn gốc yêu cầu, liên kết yêu cầu với mục tiêu kinh doanh/dự án và deliverable tương ứng." },
  { id: "m5-07", m: 5, term: "Prototype", vi: "Nguyên mẫu hoạt động của sản phẩm dự kiến, được xây dựng trước khi phát triển thật để lấy phản hồi sớm." },
  { id: "m5-08", m: 5, term: "Wireframe", vi: "Bản phác thảo giao diện (mock-up) trước khi bắt tay xây dựng thực tế." },
  { id: "m5-09", m: 5, term: "Benchmarking", vi: "So sánh chuẩn: so sánh thực hành/hiệu suất với tổ chức khác để tìm best practice." },
  { id: "m5-10", m: 5, term: "Delphi Technique", vi: "Kỹ thuật Delphi: phương pháp thu thập ý kiến ẩn danh từ hội đồng chuyên gia qua nhiều vòng để đạt đồng thuận." },
  { id: "m5-11", m: 5, term: "Product Analysis", vi: "Phân tích sản phẩm: chuyển mô tả sản phẩm cấp cao thành các deliverable cụ thể, hữu hình." },
  { id: "m5-12", m: 5, term: "Project Scope Statement", vi: "Văn kiện mô tả toàn bộ phạm vi dự án và sản phẩm, kể cả những gì bị loại trừ, giúp tránh scope creep." },
  { id: "m5-13", m: 5, term: "Work Breakdown Structure (WBS)", vi: "Cấu trúc phân rã công việc: phân cấp toàn bộ phạm vi dự án thành các work package nhỏ, dễ quản lý." },
  { id: "m5-14", m: 5, term: "Decomposition", vi: "Phân rã: kỹ thuật chia nhỏ dự án thành các thành phần công việc chi tiết hơn, dễ quản lý hơn." },
  { id: "m5-15", m: 5, term: "WBS Dictionary", vi: "Từ điển WBS: tài liệu hỗ trợ WBS, mô tả chi tiết từng thành phần công việc (code of accounts, assumptions, mốc thời gian...)." },
  { id: "m5-16", m: 5, term: "Scope Baseline", vi: "Đường cơ sở phạm vi: phiên bản đã phê duyệt của Scope Statement, WBS và WBS Dictionary; chỉ thay đổi qua kiểm soát thay đổi chính thức." },
  { id: "m5-17", m: 5, term: "MECE Principle", vi: "Nguyên tắc MECE: Mutually Exclusive (không trùng lặp) và Collectively Exhaustive (bao phủ 100% công việc — quy tắc 100%)." },
  { id: "m5-18", m: 5, term: "Work Package", vi: "Cấp thấp nhất trong WBS, là đầu vào chính để xác định các activity." },
  { id: "m5-19", m: 5, term: "Planning Package", vi: "Thành phần WBS ở cấp thấp nhất tại một thời điểm, sẽ được phân rã thành work package sau, chưa có activity." },
  { id: "m5-20", m: 5, term: "Validate Scope", vi: "Xác nhận phạm vi: quy trình chính thức chấp nhận các deliverable đã hoàn thành, do khách hàng/sponsor thực hiện (khác Control Quality)." },
  { id: "m5-21", m: 5, term: "Verify vs Validate", vi: "Verify (kiểm tra kỹ thuật nội bộ — \"làm đúng cách chưa?\") khác với Validate (xác nhận từ khách hàng — \"có phải điều đúng cần làm không?\")." },
  { id: "m5-22", m: 5, term: "Change Control Board (CCB)", vi: "Hội đồng kiểm soát thay đổi: nhóm có thẩm quyền phê duyệt hoặc từ chối các yêu cầu thay đổi của dự án." },
  { id: "m5-23", m: 5, term: "Design Thinking", vi: "Tư duy thiết kế: quy trình phi tuyến tính, lặp đi lặp lại để thấu hiểu người dùng, thách thức giả định, định nghĩa lại vấn đề và tạo ra giải pháp sáng tạo." },
  { id: "m5-24", m: 5, term: "Acceptance Criteria", vi: "Tiêu chí chấp nhận: tập hợp các điều kiện phải được đáp ứng trước khi một deliverable được chính thức chấp nhận." },
  { id: "m5-25", m: 5, term: "Requirements Management Plan", vi: "Kế hoạch quản lý yêu cầu: thành phần của kế hoạch quản lý dự án mô tả cách các yêu cầu sẽ được phân tích, tài liệu hóa và quản lý xuyên suốt dự án." },

  // ===== MODULE 6: Schedule Management =====
  { id: "m6-01", m: 6, term: "Milestone", vi: "Cột mốc: sự kiện quan trọng đánh dấu hoàn thành một deliverable lớn, luôn có thời lượng bằng 0." },
  { id: "m6-02", m: 6, term: "Schedule Management Plan", vi: "Kế hoạch quản lý tiến độ: thiết lập thủ tục, chính sách cho việc xây dựng, giám sát và kiểm soát lịch trình." },
  { id: "m6-03", m: 6, term: "Rolling Wave Planning", vi: "Lập kế hoạch cuốn chiếu: công việc gần được lên kế hoạch chi tiết, công việc xa được lên kế hoạch ở mức cao." },
  { id: "m6-04", m: 6, term: "Precedence Diagramming Method (PDM)", vi: "Phương pháp sơ đồ tiền nhiệm: kỹ thuật vẽ mạng lưới hoạt động thể hiện 4 loại quan hệ logic (FS, SS, FF, SF)." },
  { id: "m6-05", m: 6, term: "Finish-to-Start (FS)", vi: "Kết thúc-Bắt đầu: hoạt động sau chỉ bắt đầu khi hoạt động trước đã hoàn thành — loại quan hệ phổ biến nhất." },
  { id: "m6-06", m: 6, term: "Start-to-Start (SS)", vi: "Bắt đầu-Bắt đầu: hoạt động sau chỉ bắt đầu khi hoạt động trước đã bắt đầu." },
  { id: "m6-07", m: 6, term: "Finish-to-Finish (FF)", vi: "Kết thúc-Kết thúc: hoạt động sau chỉ kết thúc khi hoạt động trước đã kết thúc." },
  { id: "m6-08", m: 6, term: "Start-to-Finish (SF)", vi: "Bắt đầu-Kết thúc: hoạt động sau chỉ kết thúc khi hoạt động trước đã bắt đầu — loại quan hệ hiếm gặp nhất." },
  { id: "m6-09", m: 6, term: "Lead", vi: "Thời gian chồng lấp: hoạt động sau có thể bắt đầu sớm hơn khi hoạt động trước chưa hoàn thành hoàn toàn." },
  { id: "m6-10", m: 6, term: "Lag", vi: "Thời gian trễ: khoảng thời gian chờ bắt buộc trước khi hoạt động sau có thể bắt đầu, sau khi hoạt động trước hoàn thành." },
  { id: "m6-11", m: 6, term: "Mandatory Dependency (Hard Logic)", vi: "Phụ thuộc bắt buộc: theo yêu cầu pháp lý/hợp đồng hoặc bản chất công việc." },
  { id: "m6-12", m: 6, term: "Discretionary Dependency (Soft Logic)", vi: "Phụ thuộc tùy ý: theo thứ tự ưu tiên do đội quản lý dự án lựa chọn dựa trên best practice." },
  { id: "m6-13", m: 6, term: "External Dependency", vi: "Phụ thuộc bên ngoài: nằm ngoài tầm kiểm soát của dự án." },
  { id: "m6-14", m: 6, term: "Internal Dependency", vi: "Phụ thuộc nội bộ: nằm trong tầm kiểm soát của dự án." },
  { id: "m6-15", m: 6, term: "Three-Point Estimate (PERT)", vi: "Ước lượng ba điểm: dùng trung bình của ước lượng lạc quan, khả dĩ nhất và bi quan để tăng độ chính xác." },
  { id: "m6-16", m: 6, term: "Critical Path", vi: "Đường găng: chuỗi hoạt động có tổng thời gian dài nhất, quyết định thời gian hoàn thành ngắn nhất có thể của dự án." },
  { id: "m6-17", m: 6, term: "Float / Total Float", vi: "Độ trễ cho phép (tổng): thời gian một hoạt động có thể trễ mà không làm trễ ngày kết thúc dự án." },
  { id: "m6-18", m: 6, term: "Free Float", vi: "Độ trễ tự do: thời gian một hoạt động có thể trễ mà không ảnh hưởng đến ngày bắt đầu sớm nhất của hoạt động kế tiếp." },
  { id: "m6-19", m: 6, term: "Project Float", vi: "Độ trễ dự án: thời gian dự án có thể trễ mà không ảnh hưởng đến ngày hoàn thành do khách hàng/tổ chức áp đặt." },
  { id: "m6-20", m: 6, term: "Crashing", vi: "Rút ngắn tiến độ bằng cách thêm nguồn lực vào đường găng — hầu như luôn làm tăng chi phí." },
  { id: "m6-21", m: 6, term: "Fast Tracking", vi: "Chạy song song: thực hiện các hoạt động trên đường găng song song hoặc chồng lấp thay vì tuần tự — làm tăng rủi ro rework." },
  { id: "m6-22", m: 6, term: "Resource Leveling", vi: "Cân bằng nguồn lực: điều chỉnh lịch để cân đối nhu cầu nguồn lực, có thể làm thay đổi đường găng (thường kéo dài)." },
  { id: "m6-23", m: 6, term: "Resource Smoothing", vi: "Làm mượt nguồn lực: điều chỉnh hoạt động trong phạm vi float, không làm thay đổi đường găng." },
  { id: "m6-24", m: 6, term: "Schedule Baseline", vi: "Đường cơ sở tiến độ: phiên bản lịch trình dự án đã được phê duyệt, chỉ thay đổi qua kiểm soát thay đổi chính thức." },
  { id: "m6-25", m: 6, term: "Parkinson's Law", vi: "Định luật Parkinson: công việc sẽ tự giãn ra để lấp đầy thời gian được cho phép." },
  { id: "m6-26", m: 6, term: "Student Syndrome", vi: "Hội chứng sinh viên: xu hướng chờ đến sát hạn mới bắt đầu làm việc." },
  { id: "m6-27", m: 6, term: "Network Diagram", vi: "Sơ đồ mạng lưới: biểu diễn đồ họa các mối quan hệ logic (phụ thuộc) giữa các hoạt động trong lịch trình dự án." },
  { id: "m6-28", m: 6, term: "Gantt Chart (Bar Chart)", vi: "Biểu đồ thanh ngang thể hiện hoạt động theo trục thời gian; dùng để theo dõi tiến độ và báo cáo cho đội dự án." },
  { id: "m6-29", m: 6, term: "Milestone Chart", vi: "Biểu đồ cột mốc: tương tự Gantt nhưng chỉ hiển thị các mốc chính, thường dùng để báo cáo cho quản lý cấp cao/senior management." },
  { id: "m6-30", m: 6, term: "Critical Chain Method", vi: "Phương pháp chuỗi găng: kỹ thuật lập lịch cho phép đội dự án đặt các buffer (vùng đệm) trên bất kỳ đường nào của lịch trình để ứng phó với nguồn lực hạn chế và sự không chắc chắn của dự án." },
  { id: "m6-31", m: 6, term: "Predecessor / Successor Activity", vi: "Predecessor: hoạt động đứng trước, xảy ra trước một hoạt động phụ thuộc trong lịch trình. Successor: hoạt động đứng sau, phụ thuộc logic vào hoạt động trước đó." },
  { id: "m6-32", m: 6, term: "Forward Pass / Backward Pass", vi: "Forward Pass: kỹ thuật CPM tính ngày bắt đầu sớm (ES) và kết thúc sớm (EF) bằng cách đi xuôi từ đầu lịch trình. Backward Pass: tính ngày bắt đầu trễ (LS) và kết thúc trễ (LF) bằng cách đi ngược từ cuối lịch trình." },
  { id: "m6-33", m: 6, term: "Schedule Compression", vi: "Nén tiến độ: kỹ thuật rút ngắn thời gian lịch trình mà không giảm phạm vi dự án — gồm 2 kỹ thuật chính: Crashing và Fast Tracking." },
  { id: "m6-34", m: 6, term: "ES / EF / LS / LF Dates", vi: "4 mốc thời gian dùng trong Critical Path Method: Early Start/Early Finish (tính từ Forward Pass — sớm nhất có thể bắt đầu/kết thúc), Late Start/Late Finish (tính từ Backward Pass — trễ nhất có thể bắt đầu/kết thúc mà không ảnh hưởng ngày hoàn thành dự án)." },

  // ===== MODULE 7: Agile & Scrum =====
  { id: "m7-01", m: 7, term: "Agile Manifesto", vi: "Tuyên ngôn Agile (2001): 4 giá trị cốt lõi ưu tiên con người, sản phẩm hoạt động, hợp tác với khách hàng và thích ứng với thay đổi." },
  { id: "m7-02", m: 7, term: "Scrum", vi: "Khung làm việc (framework) nhẹ, giúp giải quyết các vấn đề thích ứng phức tạp trong khi tạo ra sản phẩm giá trị cao nhất có thể." },
  { id: "m7-03", m: 7, term: "Complex Adaptive System (CAS)", vi: "Hệ thống thích ứng phức tạp: nhiều tác nhân tự trị tương tác, hình thành trật tự \"nổi lên\" (emergent order) từ chính hệ thống." },
  { id: "m7-04", m: 7, term: "Product Owner", vi: "Vai trò chịu trách nhiệm tối đa hóa giá trị sản phẩm, quản lý Product Backlog và chấp nhận/từ chối kết quả công việc." },
  { id: "m7-05", m: 7, term: "Scrum Master", vi: "Vai trò huấn luyện đội ngũ tự tổ chức, đa chức năng, và loại bỏ trở ngại cho tiến độ của Development Team." },
  { id: "m7-06", m: 7, term: "Development Team (Developers)", vi: "Nhóm chuyên gia thực hiện công việc tạo ra Increment sản phẩm mỗi Sprint." },
  { id: "m7-07", m: 7, term: "Product Backlog", vi: "Danh sách ưu tiên tất cả công việc cần làm để xây dựng sản phẩm, do Product Owner quản lý, luôn được cập nhật động." },
  { id: "m7-08", m: 7, term: "Backlog Refinement (Grooming)", vi: "Tinh chỉnh backlog: bổ sung chi tiết, điều chỉnh ước lượng và độ ưu tiên của các mục trong backlog." },
  { id: "m7-09", m: 7, term: "Sprint Backlog", vi: "Tập con của Product Backlog được chọn làm mục tiêu cho Sprint cụ thể, do Development Team lựa chọn." },
  { id: "m7-10", m: 7, term: "Sprint/Iteration", vi: "Khung thời gian cố định (timebox) để tạo ra một Increment sản phẩm hoàn chỉnh — giống như một dự án thu nhỏ." },
  { id: "m7-11", m: 7, term: "Daily Scrum", vi: "Họp đứng 15 phút hàng ngày, cùng thời gian - cùng địa điểm, để đồng bộ tiến độ và lập kế hoạch cho 24 giờ tiếp theo." },
  { id: "m7-12", m: 7, term: "Sprint Planning", vi: "Họp lập kế hoạch Sprint: cả đội thảo luận và cam kết những gì sẽ hoàn thành trong Sprint." },
  { id: "m7-13", m: 7, term: "Sprint Review", vi: "Họp không chính thức trình bày Increment cho Product Owner để lấy phản hồi — không phải họp báo cáo trạng thái." },
  { id: "m7-14", m: 7, term: "Sprint Retrospective", vi: "Họp nhìn lại Sprint: đội thẳng thắn thảo luận điều gì tốt, chưa tốt và cải tiến gì cho Sprint tiếp theo." },
  { id: "m7-15", m: 7, term: "Definition of Done (DoD)", vi: "Định nghĩa hoàn thành: tiêu chí chung được thống nhất để xác định một công việc thực sự đã hoàn tất." },
  { id: "m7-16", m: 7, term: "User Story", vi: "Câu chuyện người dùng theo mẫu \"As a [vai trò], I want [mục tiêu], So that [lý do]\"." },
  { id: "m7-17", m: 7, term: "INVEST Criteria", vi: "Tiêu chí đánh giá user story tốt: Independent, Negotiable, Valuable, Estimable, Small, Testable." },
  { id: "m7-18", m: 7, term: "Self-Organizing Team", vi: "Đội tự tổ chức: tự quyết định cách thực hiện công việc thay vì được chỉ đạo từ bên ngoài." },
  { id: "m7-19", m: 7, term: "Cross-functional Team", vi: "Đội đa chức năng: có đầy đủ kỹ năng cần thiết để hoàn thành công việc mà không phụ thuộc bên ngoài." },
  { id: "m7-20", m: 7, term: "T-shaped vs I-shaped Skill", vi: "T-shaped: giỏi một lĩnh vực nhưng có thể hỗ trợ lĩnh vực khác; I-shaped: chỉ giỏi chuyên sâu một lĩnh vực duy nhất." },
  { id: "m7-21", m: 7, term: "Timebox", vi: "Khung thời gian cố định không thay đổi cho một hoạt động hoặc sự kiện (Sprint, Daily Scrum...)." },
  { id: "m7-22", m: 7, term: "Definition of Ready (DoR)", vi: "Định nghĩa sẵn sàng: tiêu chí xác định một hạng mục backlog đã đủ rõ ràng, chi tiết để có thể đưa vào Sprint tiếp theo." },
  { id: "m7-23", m: 7, term: "Spike", vi: "Hoạt động nghiên cứu/thử nghiệm ngắn nhằm giảm rủi ro kỹ thuật hoặc làm rõ yêu cầu trước khi ước lượng chính thức một story." },
  { id: "m7-24", m: 7, term: "Impediment (Blocker)", vi: "Trở ngại: bất kỳ rào cản nào ngăn đội đạt được mục tiêu; thường được nêu ra trong Daily Scrum để Scrum Master hỗ trợ tháo gỡ." },
  { id: "m7-25", m: 7, term: "Increment", vi: "Phần tăng trưởng sản phẩm: một deliverable có chức năng, đã được kiểm thử và chấp nhận, là kết quả đầu ra của mỗi Sprint và là một phần của tổng thể sản phẩm dự án." },

  // ===== MODULE 8: Adaptive Planning & Value Delivery =====
  { id: "m8-01", m: 8, term: "MoSCoW", vi: "Kỹ thuật ưu tiên hóa: Must have, Should have, Could have, Would like to have (Won't have)." },
  { id: "m8-02", m: 8, term: "Kano Model", vi: "Mô hình Kano phân loại tính năng theo mức độ hài lòng khách hàng: Delighters/Exciters, Satisfiers, Dissatisfiers, Indifferent." },
  { id: "m8-03", m: 8, term: "Minimum Viable Product (MVP)", vi: "Sản phẩm khả dụng tối thiểu: đủ chức năng để hữu ích với người dùng nhưng vẫn đủ nhỏ để triển khai nhanh." },
  { id: "m8-04", m: 8, term: "Kanban", vi: "Phương pháp trực quan hóa luồng công việc qua bảng Kanban (To Do - In Progress - Done)." },
  { id: "m8-05", m: 8, term: "Work In Progress (WIP)", vi: "Công việc đang thực hiện nhưng chưa hoàn thành; tiêu tốn nguồn lực nhưng chưa mang lại giá trị." },
  { id: "m8-06", m: 8, term: "WIP Limit", vi: "Giới hạn công việc đang thực hiện: giới hạn số lượng task ở mỗi giai đoạn để tránh quá tải và tối ưu luồng công việc." },
  { id: "m8-07", m: 8, term: "Little's Law", vi: "Định luật Little: Cycle Time = Work In Progress / Throughput." },
  { id: "m8-08", m: 8, term: "Cumulative Flow Diagram (CFD)", vi: "Biểu đồ luồng tích lũy: công cụ theo dõi và dự báo tiến độ giao hàng, phát hiện bottleneck." },
  { id: "m8-09", m: 8, term: "Cycle Time", vi: "Thời gian chu kỳ: thời gian từ khi bắt đầu thực hiện đến khi hoàn thành một hạng mục công việc." },
  { id: "m8-10", m: 8, term: "Lead Time", vi: "Thời gian dẫn: thời gian từ khi có yêu cầu đến khi hoàn thành và bàn giao." },
  { id: "m8-11", m: 8, term: "Throughput", vi: "Thông lượng: số lượng hạng mục công việc hoàn thành trong một đơn vị thời gian." },
  { id: "m8-12", m: 8, term: "Theory of Constraints", vi: "Lý thuyết ràng buộc: tìm và cải thiện điểm nghẽn (constraint) của hệ thống để đạt hiệu quả tổng thể tốt nhất." },
  { id: "m8-13", m: 8, term: "Story Point", vi: "Đơn vị đo tương đối dùng để ước lượng nỗ lực tổng thể cần thiết cho một user story (độ phức tạp, khối lượng công việc, mức độ không chắc chắn)." },
  { id: "m8-14", m: 8, term: "Planning Poker", vi: "Kỹ thuật ước lượng nhóm dùng thẻ bài theo dãy Fibonacci để đạt đồng thuận về story point." },
  { id: "m8-15", m: 8, term: "Velocity", vi: "Tốc độ: khối lượng công việc (tính bằng story point) mà đội hoàn thành trong một Sprint." },
  { id: "m8-16", m: 8, term: "Affinity Estimating", vi: "Ước lượng theo nhóm tương đồng: nhóm các hạng mục có độ lớn tương tự lại với nhau để so sánh nhanh." },
  { id: "m8-17", m: 8, term: "T-shirt Sizing", vi: "Ước lượng theo cỡ áo (XS, S, M, L, XL, XXL): công cụ ước lượng thô ở giai đoạn đầu dự án." },
  { id: "m8-18", m: 8, term: "Product Vision Statement", vi: "Tuyên bố tầm nhìn sản phẩm: mô tả ngắn gọn sản phẩm là gì, dành cho ai và khác biệt so với đối thủ ra sao." },
  { id: "m8-19", m: 8, term: "Story Map", vi: "Bản đồ câu chuyện: công cụ trực quan sắp xếp ưu tiên user story theo luồng chức năng cốt lõi (backbone)." },
  { id: "m8-20", m: 8, term: "Test-Driven Development (TDD)", vi: "Phát triển hướng kiểm thử: viết test trước khi viết code (Red - Green - Refactor)." },
  { id: "m8-21", m: 8, term: "Acceptance Test-Driven Development (ATDD)", vi: "Phát triển hướng kiểm thử chấp nhận: chuyển trọng tâm kiểm thử sang yêu cầu nghiệp vụ, làm rõ Definition of Done ở mức chi tiết." },
  { id: "m8-22", m: 8, term: "Continuous Integration (CI)", vi: "Tích hợp liên tục: thường xuyên gộp code mới vào kho lưu trữ chung, kết hợp kiểm thử tự động để phát hiện lỗi sớm." },
  { id: "m8-23", m: 8, term: "Exploratory Testing", vi: "Kiểm thử khám phá: dựa vào kỹ năng và sự sáng tạo của tester để phát hiện lỗi ngoài kịch bản có sẵn." },
  { id: "m8-24", m: 8, term: "Epic", vi: "Câu chuyện người dùng lớn, kéo dài qua nhiều Sprint, cần được chia nhỏ (sliced) thành các story nhỏ hơn." },
  { id: "m8-25", m: 8, term: "Card-Conversation-Confirmation (3Cs)", vi: "Ba yếu tố của user story: Card (thẻ ghi tóm tắt), Conversation (trao đổi làm rõ), Confirmation (xác nhận tiêu chí chấp nhận)." },
  { id: "m8-26", m: 8, term: "Value vs Non-value vs Anti-value", vi: "Value (đóng góp trực tiếp mục tiêu), Non-value/Waste (không đóng góp nhưng tốn công), Anti-value (gây hại cho mục tiêu)." },
  { id: "m8-27", m: 8, term: "Burndown Chart", vi: "Biểu đồ giảm dần: thể hiện khối lượng công việc còn lại theo thời gian trong một Sprint/Release; đường lý tưởng đi xuống dần về 0." },
  { id: "m8-28", m: 8, term: "Burnup Chart", vi: "Biểu đồ tăng dần: thể hiện khối lượng công việc đã hoàn thành theo thời gian, đồng thời có thể hiển thị thay đổi tổng phạm vi (scope) trong dự án." },
  { id: "m8-29", m: 8, term: "Continuous Delivery (CD)", vi: "Giao hàng liên tục: thực hành chuyển giao các gói tính năng tăng dần đến khách hàng ngay lập tức, thường qua các lô công việc nhỏ kết hợp tự động hóa." },
  { id: "m8-30", m: 8, term: "DevOps", vi: "Tập hợp các thực hành nhằm tạo luồng giao hàng mượt mà bằng cách cải thiện sự hợp tác giữa đội phát triển (Dev) và đội vận hành (Ops)." },
  { id: "m8-31", m: 8, term: "Technical Debt", vi: "Nợ kỹ thuật: chi phí bị trì hoãn của công việc chưa được làm đúng cách ở giai đoạn trước trong vòng đời sản phẩm, sẽ phải trả giá (khắc phục) về sau." },
  { id: "m8-32", m: 8, term: "Value Stream", vi: "Dòng giá trị: cấu trúc tổ chức tập trung vào luồng giá trị chảy đến khách hàng thông qua việc cung cấp sản phẩm/dịch vụ cụ thể." },
  { id: "m8-33", m: 8, term: "Release Planning", vi: "Lập kế hoạch phát hành: quá trình xác định kế hoạch cấp cao cho việc phát hành hoặc chuyển giao một sản phẩm/deliverable/increment giá trị đến khách hàng, thường trải qua nhiều iteration." },

  // ===== MODULE 9: Financial Management =====
  { id: "m9-01", m: 9, term: "CapEx (Capital Expenditure)", vi: "Chi phí đầu tư: khoản đầu tư để mua, nâng cấp tài sản vật chất dài hạn (bất động sản, thiết bị, công nghệ)." },
  { id: "m9-02", m: 9, term: "OpEx (Operational Expenditure)", vi: "Chi phí vận hành: chi phí hàng ngày để duy trì hoạt động kinh doanh (quảng cáo, lương, tiện ích...)." },
  { id: "m9-03", m: 9, term: "Direct Cost", vi: "Chi phí trực tiếp: chi phí gắn trực tiếp với công việc của dự án, không chia sẻ với dự án khác." },
  { id: "m9-04", m: 9, term: "Indirect Cost", vi: "Chi phí gián tiếp: chi phí overhead phục vụ nhiều dự án cùng lúc (thuế, đào tạo, license phần mềm...)." },
  { id: "m9-05", m: 9, term: "Fixed Cost", vi: "Chi phí cố định: không đổi trong suốt dự án (VD: tiền thuê văn phòng)." },
  { id: "m9-06", m: 9, term: "Variable Cost", vi: "Chi phí biến đổi: thay đổi theo khối lượng công việc/sản xuất." },
  { id: "m9-07", m: 9, term: "Rough Order of Magnitude (ROM)", vi: "Ước lượng sơ bộ ở giai đoạn khởi tạo dự án, độ chính xác -25% đến +75%." },
  { id: "m9-08", m: 9, term: "Budget Estimate", vi: "Ước lượng ngân sách ở giai đoạn lập kế hoạch, độ chính xác -10% đến +25%." },
  { id: "m9-09", m: 9, term: "Definitive Estimate", vi: "Ước lượng xác định, độ chính xác cao nhất -5% đến +10%, được tinh chỉnh dần khi dự án tiến triển." },
  { id: "m9-10", m: 9, term: "Contingency Reserve", vi: "Dự phòng cho rủi ro đã biết (known-unknowns), thuộc cost baseline, PM thường có quyền sử dụng." },
  { id: "m9-11", m: 9, term: "Management Reserve", vi: "Dự phòng quản lý cho rủi ro chưa biết (unknown-unknowns), nằm ngoài cost baseline, cần phê duyệt thay đổi mới được dùng." },
  { id: "m9-12", m: 9, term: "Cost Baseline", vi: "Đường cơ sở chi phí: ngân sách theo thời gian đã phê duyệt, bao gồm contingency reserve nhưng không gồm management reserve." },
  { id: "m9-13", m: 9, term: "Funding Limit Reconciliation", vi: "Điều hòa giới hạn tài trợ: cách tổ chức quản lý dòng tiền, đối chiếu nhu cầu tài trợ với thực tế cấp vốn." },
  { id: "m9-14", m: 9, term: "Planned Value (PV)", vi: "Giá trị kế hoạch: ngân sách được phê duyệt cho công việc dự kiến hoàn thành đến một thời điểm." },
  { id: "m9-15", m: 9, term: "Earned Value (EV)", vi: "Giá trị thu được: giá trị (theo tiền) của công việc thực tế đã hoàn thành. Công thức: EV = % hoàn thành thực tế × BAC." },
  { id: "m9-16", m: 9, term: "Actual Cost (AC)", vi: "Chi phí thực tế: chi phí thực sự đã chi ra để hoàn thành công việc đến thời điểm hiện tại." },
  { id: "m9-17", m: 9, term: "Budget at Completion (BAC)", vi: "Tổng ngân sách được phê duyệt cho toàn bộ dự án." },
  { id: "m9-18", m: 9, term: "Schedule Variance (SV)", vi: "Sai lệch tiến độ. Công thức: SV = EV − PV; SV > 0 nghĩa là vượt tiến độ (ahead of schedule)." },
  { id: "m9-19", m: 9, term: "Cost Variance (CV)", vi: "Sai lệch chi phí. Công thức: CV = EV − AC; CV > 0 nghĩa là dưới ngân sách (under budget)." },
  { id: "m9-20", m: 9, term: "Schedule Performance Index (SPI)", vi: "Chỉ số hiệu suất tiến độ. Công thức: SPI = EV/PV; SPI > 1 là hiệu suất tốt." },
  { id: "m9-21", m: 9, term: "Cost Performance Index (CPI)", vi: "Chỉ số hiệu suất chi phí. Công thức: CPI = EV/AC; CPI > 1 là hiệu suất tốt." },
  { id: "m9-22", m: 9, term: "Estimate at Completion (EAC)", vi: "Ước lượng tổng chi phí khi hoàn thành dự án. Công thức phổ biến nhất: EAC = BAC/CPI (giả định hiệu suất chi phí hiện tại sẽ tiếp diễn cho phần việc còn lại). Nếu ước lượng lại toàn bộ phần còn lại từ đầu (bottom-up): EAC = AC + ETC." },
  { id: "m9-23", m: 9, term: "Estimate to Complete (ETC)", vi: "Ước lượng chi phí còn cần để hoàn thành phần việc còn lại. Công thức: ETC = EAC − AC." },
  { id: "m9-24", m: 9, term: "Variance at Completion (VAC)", vi: "Sai lệch tại thời điểm hoàn thành. Công thức: VAC = BAC − EAC." },
  { id: "m9-25", m: 9, term: "To-Complete Performance Index (TCPI)", vi: "Chỉ số hiệu suất chi phí cần đạt cho phần việc còn lại để hoàn thành đúng mục tiêu ngân sách. Công thức theo BAC: TCPI = (BAC − EV) / (BAC − AC); nếu ngân sách gốc không còn khả thi, dùng theo EAC: TCPI = (BAC − EV) / (EAC − AC). TCPI > 1 nghĩa là khó hoàn thành hơn (cần hiệu suất cao hơn mức đã đạt được)." },
  { id: "m9-26", m: 9, term: "Value Engineering (Value Analysis)", vi: "Phân tích giá trị: tìm cách thực hiện cùng công việc với chi phí thấp hơn." },
  { id: "m9-27", m: 9, term: "Earned Value Management (EVM)", vi: "Phương pháp luận kết hợp đo lường phạm vi, tiến độ, chi phí và nguồn lực để đánh giá hiệu suất và tiến độ dự án — nền tảng cho các chỉ số PV/EV/AC/SPI/CPI." },
  { id: "m9-28", m: 9, term: "Project Budget", vi: "Tổng ngân sách dự án. Công thức: Project Budget = tổng ước lượng chi phí work package + Contingency Reserve + Management Reserve." },
  { id: "m9-29", m: 9, term: "Performance Measurement Baseline (PMB)", vi: "Đường cơ sở đo lường hiệu suất: tích hợp scope baseline, schedule baseline và cost baseline để làm cơ sở so sánh, quản lý và kiểm soát việc thực thi dự án." },
  { id: "m9-30", m: 9, term: "S-Curve Analysis", vi: "Phân tích đường cong chữ S: kỹ thuật thể hiện xu hướng hiệu suất bằng đồ thị chi phí lũy kế theo thời gian, thường thấp lúc đầu và cao dần về cuối dự án." },
  { id: "m9-31", m: 9, term: "Total Cost of Ownership (TCO)", vi: "Tổng chi phí sở hữu: ước lượng tài chính giúp xác định toàn bộ chi phí trực tiếp và gián tiếp của một sản phẩm/dịch vụ trong suốt vòng đời sử dụng." },
  { id: "m9-32", m: 9, term: "Earning Rules (0/100, 50/50, Milestone, % Complete)", vi: "Các quy tắc ghi nhận Earned Value cho work package: 0/100 (chỉ ghi nhận 100% khi hoàn thành, dùng cho công việc ngắn); 50/50 (50% khi bắt đầu, 50% khi xong); Milestone (chia theo % tại từng mốc, dùng cho công việc dài có nhiều giai đoạn); % Complete (ước lượng % hoàn thành chủ quan — ít đáng tin cậy nhất)." },
  { id: "m9-33", m: 9, term: "Cost-Benefit Analysis", vi: "Phân tích chi phí - lợi ích: phương pháp tài chính so sánh lợi ích dự kiến thu được với chi phí bỏ ra, dùng để quyết định có nên đầu tư hay không (khác BCR ở chỗ đây là phân tích tổng quát, không chỉ ra một tỷ lệ cụ thể)." },

  // ===== MODULE 10: Quality Management =====
  { id: "m10-01", m: 10, term: "Quality", vi: "Chất lượng: mức độ mà một tập hợp các đặc tính vốn có đáp ứng yêu cầu (định nghĩa theo ISO 9000)." },
  { id: "m10-02", m: 10, term: "Grade", vi: "Cấp độ/hạng: sự khác biệt về tính năng của sản phẩm, khác với chất lượng — một sản phẩm cấp thấp vẫn phải đảm bảo chất lượng cao." },
  { id: "m10-03", m: 10, term: "Accuracy vs Precision", vi: "Accuracy (độ chính xác: giá trị đo gần với giá trị thật) khác với Precision (độ chụm: các lần đo gần nhau, ít phân tán)." },
  { id: "m10-04", m: 10, term: "Cost of Quality (CoQ)", vi: "Chi phí chất lượng: tổng chi phí bỏ ra trong suốt vòng đời sản phẩm để phòng ngừa không phù hợp, đánh giá và xử lý lỗi." },
  { id: "m10-05", m: 10, term: "Prevention Cost", vi: "Chi phí phòng ngừa: chi phí xây dựng chất lượng ngay từ đầu (đào tạo, tài liệu hóa quy trình)." },
  { id: "m10-06", m: 10, term: "Appraisal Cost", vi: "Chi phí thẩm định: chi phí đánh giá chất lượng (kiểm tra, thử nghiệm)." },
  { id: "m10-07", m: 10, term: "Internal Failure Cost", vi: "Chi phí lỗi nội bộ: chi phí do lỗi được phát hiện trước khi bàn giao (rework, phế phẩm)." },
  { id: "m10-08", m: 10, term: "External Failure Cost", vi: "Chi phí lỗi bên ngoài: chi phí do lỗi khách hàng phát hiện (bảo hành, mất uy tín)." },
  { id: "m10-09", m: 10, term: "Cost of Conformance vs Non-conformance", vi: "Chi phí tuân thủ (phòng ngừa + thẩm định, chi trong dự án để tránh lỗi) khác với chi phí không tuân thủ (lỗi nội bộ + lỗi bên ngoài, phát sinh do thất bại)." },
  { id: "m10-10", m: 10, term: "Quality Audit", vi: "Đánh giá chất lượng độc lập, có cấu trúc, để xác định hoạt động dự án có tuân thủ chính sách/quy trình hay không." },
  { id: "m10-11", m: 10, term: "Quality Checklist", vi: "Danh sách kiểm tra chất lượng: công cụ có cấu trúc để xác minh các bước bắt buộc đã được thực hiện." },
  { id: "m10-12", m: 10, term: "PDCA (Plan-Do-Check-Act)", vi: "Chu trình cải tiến liên tục Plan-Do-Check-Act (Deming Cycle)." },
  { id: "m10-13", m: 10, term: "Six Sigma", vi: "Phương pháp quản lý chất lượng dựa trên số liệu thống kê nhằm giảm thiểu lỗi/biến động trong quy trình." },
  { id: "m10-14", m: 10, term: "Kaizen", vi: "Triết lý cải tiến liên tục của Nhật Bản: cải thiện chất lượng con người trước rồi mới đến sản phẩm/dịch vụ." },
  { id: "m10-15", m: 10, term: "Lean", vi: "Phương pháp sản xuất tinh gọn (gốc từ Toyota), tập trung loại bỏ lãng phí." },
  { id: "m10-16", m: 10, term: "Flowchart (Lưu đồ)", vi: "Biểu diễn đồ họa các bước trong một quy trình, giúp xác định nơi có thể xảy ra lỗi chất lượng." },
  { id: "m10-17", m: 10, term: "Control Chart", vi: "Biểu đồ kiểm soát: xác định một quy trình có đang trong tầm kiểm soát (ổn định, dự đoán được) hay không." },
  { id: "m10-18", m: 10, term: "Rule of Seven", vi: "Quy tắc bảy điểm: 7 điểm dữ liệu liên tiếp nằm cùng một phía so với giá trị trung bình được coi là mất kiểm soát dù vẫn nằm trong control limit." },
  { id: "m10-19", m: 10, term: "Check Sheet", vi: "Phiếu kiểm tra: công cụ thu thập dữ liệu thời gian thực ngay tại nơi dữ liệu phát sinh." },
  { id: "m10-20", m: 10, term: "Histogram", vi: "Biểu đồ cột thể hiện phân bố dữ liệu, giúp thấy vấn đề nào đáng quan tâm nhất." },
  { id: "m10-21", m: 10, term: "Pareto Chart (Quy tắc 80/20)", vi: "Biểu đồ Pareto: 80% vấn đề xuất phát từ 20% nguyên nhân gốc rễ, giúp ưu tiên xử lý." },
  { id: "m10-22", m: 10, term: "Fishbone Diagram (Ishikawa)", vi: "Biểu đồ xương cá: công cụ phân tích nguyên nhân gốc rễ (root cause analysis) của một vấn đề." },
  { id: "m10-23", m: 10, term: "Scatter Diagram", vi: "Biểu đồ phân tán: thể hiện mối quan hệ giữa hai biến số, điểm càng gần đường chéo thì tương quan càng chặt." },
  { id: "m10-24", m: 10, term: "Quality Assurance (QA) vs Quality Control (QC)", vi: "QA tập trung phòng ngừa và cải tiến quy trình (proactive), QC tập trung kiểm tra deliverable thực tế (reactive)." },

  // ===== MODULE 11: Risk Management =====
  { id: "m11-01", m: 11, term: "Risk", vi: "Rủi ro: sự kiện hoặc điều kiện không chắc chắn mà nếu xảy ra sẽ ảnh hưởng (tích cực hoặc tiêu cực) đến ít nhất một mục tiêu dự án." },
  { id: "m11-02", m: 11, term: "Issue", vi: "Vấn đề: khi một rủi ro đã xảy ra, sự không chắc chắn trở thành chắc chắn và được gọi là issue." },
  { id: "m11-03", m: 11, term: "Probability", vi: "Xác suất xảy ra của rủi ro, luôn nằm trong khoảng lớn hơn 0% và nhỏ hơn 100%." },
  { id: "m11-04", m: 11, term: "Impact", vi: "Mức độ ảnh hưởng của rủi ro đến chi phí, tiến độ hoặc mục tiêu dự án khác." },
  { id: "m11-05", m: 11, term: "Threat vs Opportunity", vi: "Threat (rủi ro tiêu cực) và Opportunity (rủi ro tích cực) — cả hai đều là \"risk\" theo định nghĩa PMI." },
  { id: "m11-06", m: 11, term: "Known Risk (Known-Unknown)", vi: "Rủi ro đã biết: đội dự án nhận thức được và có thể phân tích trước." },
  { id: "m11-07", m: 11, term: "Unknown Risk (Unknown-Unknown)", vi: "Rủi ro chưa biết: đội dự án không thể nhận diện hay phân tích trước, cần dự phòng bằng management reserve." },
  { id: "m11-08", m: 11, term: "Individual Risk vs Overall Project Risk", vi: "Individual risk (rủi ro cụ thể, ghi trong risk register) khác với Overall risk (mức độ rủi ro tổng thể của cả dự án, ảnh hưởng đến việc lựa chọn dự án)." },
  { id: "m11-09", m: 11, term: "Risk Attitude", vi: "Thái độ với rủi ro: cách một cá nhân/tổ chức phản ứng trước sự không chắc chắn (risk-averse, risk-seeking, risk-neutral)." },
  { id: "m11-10", m: 11, term: "Risk Appetite", vi: "Khẩu vị rủi ro: mức độ và loại rủi ro mà tổ chức sẵn sàng chấp nhận để theo đuổi mục tiêu." },
  { id: "m11-11", m: 11, term: "Risk Threshold", vi: "Ngưỡng rủi ro: điểm cụ thể mà tại đó mức rủi ro trở nên không thể chấp nhận được." },
  { id: "m11-12", m: 11, term: "Risk Breakdown Structure (RBS)", vi: "Cấu trúc phân cấp các nguồn/danh mục rủi ro của dự án." },
  { id: "m11-13", m: 11, term: "Prompt List", vi: "Danh sách gợi ý các danh mục rủi ro được định trước, dùng làm khung hỗ trợ nhận diện rủi ro." },
  { id: "m11-14", m: 11, term: "Risk Register", vi: "Sổ đăng ký rủi ro: tài liệu ghi nhận rủi ro đã nhận diện, chủ sở hữu rủi ro tiềm năng và phản ứng rủi ro tiềm năng." },
  { id: "m11-15", m: 11, term: "Risk Report", vi: "Báo cáo rủi ro: tổng hợp thông tin về nguồn gốc rủi ro tổng thể và các rủi ro cá nhân quan trọng nhất của dự án." },
  { id: "m11-16", m: 11, term: "Qualitative Risk Analysis", vi: "Phân tích rủi ro định tính: đánh giá ưu tiên rủi ro dựa trên xác suất và mức độ ảnh hưởng (mang tính chủ quan)." },
  { id: "m11-17", m: 11, term: "Risk Score (Probability × Impact)", vi: "Điểm rủi ro dùng để xếp hạng ưu tiên rủi ro. Công thức: Risk Score = Probability × Impact." },
  { id: "m11-18", m: 11, term: "Quantitative Risk Analysis", vi: "Phân tích rủi ro định lượng: phân tích số học ảnh hưởng tổng thể của rủi ro lên mục tiêu dự án." },
  { id: "m11-19", m: 11, term: "Expected Monetary Value (EMV)", vi: "Giá trị tiền tệ kỳ vọng, hỗ trợ tính toán dự phòng ngân sách. Công thức: EMV = Probability × Impact." },
  { id: "m11-20", m: 11, term: "Decision Tree", vi: "Cây quyết định: công cụ trực quan hóa các lựa chọn và kết quả tài chính kỳ vọng để hỗ trợ ra quyết định." },
  { id: "m11-21", m: 11, term: "Monte Carlo Simulation", vi: "Mô phỏng Monte Carlo: mô phỏng máy tính chạy nhiều kịch bản \"what-if\" để dự đoán khả năng đạt mục tiêu dự án." },
  { id: "m11-22", m: 11, term: "Sensitivity Analysis", vi: "Phân tích độ nhạy: xác định rủi ro/nguồn không chắc chắn nào có tiềm năng ảnh hưởng lớn nhất đến kết quả dự án." },
  { id: "m11-23", m: 11, term: "Risk Response Strategies (Threats)", vi: "Chiến lược ứng phó rủi ro tiêu cực: Escalate (leo thang), Avoid (né tránh), Mitigate (giảm thiểu), Transfer (chuyển giao), Accept (chấp nhận)." },
  { id: "m11-24", m: 11, term: "Risk Response Strategies (Opportunities)", vi: "Chiến lược ứng phó rủi ro tích cực: Escalate, Exploit (khai thác), Enhance (tăng cường), Share (chia sẻ), Accept (chấp nhận)." },
  { id: "m11-25", m: 11, term: "Passive vs Active Acceptance", vi: "Passive acceptance (không hành động, xử lý khi xảy ra) khác với Active acceptance (lập sẵn contingency plan)." },
  { id: "m11-26", m: 11, term: "Contingency Plan", vi: "Kế hoạch dự phòng: hành động đã lên kế hoạch trước, sẽ kích hoạt khi rủi ro xảy ra (dùng contingency reserve)." },
  { id: "m11-27", m: 11, term: "Fallback Plan", vi: "Kế hoạch dự phòng thay thế: kích hoạt khi contingency plan không hiệu quả." },
  { id: "m11-28", m: 11, term: "Residual Risk", vi: "Rủi ro còn sót lại: rủi ro vẫn tồn tại sau khi đã thực hiện các phản ứng rủi ro có chủ đích." },
  { id: "m11-29", m: 11, term: "Secondary Risk", vi: "Rủi ro thứ cấp: rủi ro mới phát sinh trực tiếp do việc triển khai một phản ứng rủi ro khác." },
  { id: "m11-30", m: 11, term: "Risk Owner", vi: "Chủ sở hữu rủi ro: người chịu trách nhiệm lập kế hoạch phản ứng phù hợp và đảm bảo nó được thực hiện." },
  { id: "m11-31", m: 11, term: "Risk Audit", vi: "Đánh giá hiệu quả của risk owner trong việc triển khai phản ứng rủi ro, cũng như hiệu quả của toàn bộ quy trình quản lý rủi ro." },
  { id: "m11-32", m: 11, term: "SWOT Analysis", vi: "Phân tích Điểm mạnh - Điểm yếu - Cơ hội - Thách thức (Strengths, Weaknesses, Opportunities, Threats) — một kỹ thuật nhận diện rủi ro." },
  { id: "m11-33", m: 11, term: "Risk Categories (RBS Level 1)", vi: "4 nhóm nguồn rủi ro cấp cao nhất thường dùng trong Risk Breakdown Structure (RBS): Technical (kỹ thuật), External (bên ngoài), Organizational (tổ chức), Project Management (quản lý dự án)." },
  { id: "m11-34", m: 11, term: "Watch List", vi: "Danh sách theo dõi: các rủi ro có mức ưu tiên thấp, không cần phản ứng ngay nhưng vẫn được giám sát định kỳ trong Monitor Risk." },
  { id: "m11-35", m: 11, term: "Risk Management Plan", vi: "Kế hoạch quản lý rủi ro: thành phần của kế hoạch quản lý dự án mô tả cách các hoạt động quản lý rủi ro sẽ được cấu trúc và thực hiện." },
  { id: "m11-36", m: 11, term: "Reserve Analysis", vi: "Phân tích dự phòng: đánh giá lượng rủi ro còn lại của dự án so với lượng dự phòng thời gian/ngân sách còn lại, để xác định dự phòng có còn đủ hay không." },
  { id: "m11-37", m: 11, term: "Risk Exposure", vi: "Mức độ phơi nhiễm rủi ro: thước đo tổng hợp về tác động tiềm tàng của tất cả rủi ro tại một thời điểm bất kỳ trong dự án." },
  { id: "m11-38", m: 11, term: "Trigger Condition", vi: "Điều kiện kích hoạt: sự kiện hoặc tình huống báo hiệu rằng một rủi ro sắp xảy ra, dùng để kích hoạt contingency plan." },
  { id: "m11-39", m: 11, term: "Workaround", vi: "Giải pháp tình thế: phản ứng tức thời, tạm thời trước một rủi ro đã xảy ra mà chưa có phản ứng được lên kế hoạch trước, hoặc phản ứng đã lên kế hoạch không hiệu quả." },
  { id: "m11-40", m: 11, term: "PESTLE Analysis", vi: "Công cụ hoạch định chiến lược đánh giá có hệ thống các yếu tố Political, Economic, Sociocultural, Technological, Legal, Environmental — giúp nhìn nhận môi trường bên ngoài dự án (thuộc Domain III)." },
  { id: "m11-41", m: 11, term: "Risk Avoidance", vi: "Né tránh rủi ro: loại bỏ hoàn toàn threat hoặc bảo vệ dự án khỏi tác động của nó (VD: thay đổi kế hoạch để loại bỏ nguyên nhân gây rủi ro)." },
  { id: "m11-42", m: 11, term: "Risk Mitigation", vi: "Giảm thiểu rủi ro: hành động làm giảm xác suất xảy ra và/hoặc mức độ ảnh hưởng của một threat xuống ngưỡng có thể chấp nhận được." },
  { id: "m11-43", m: 11, term: "Risk Transference", vi: "Chuyển giao rủi ro: dịch chuyển tác động của threat cùng với quyền sở hữu phản ứng sang bên thứ ba (VD: mua bảo hiểm, thuê ngoài qua hợp đồng)." },
  { id: "m11-44", m: 11, term: "Risk Exploiting", vi: "Khai thác rủi ro: hành động chủ động để đảm bảo một opportunity chắc chắn xảy ra, thay vì chỉ hy vọng nó xảy ra." },
  { id: "m11-45", m: 11, term: "Risk Enhancement", vi: "Tăng cường rủi ro: hành động làm tăng xác suất xảy ra và/hoặc mức độ tác động tích cực của một opportunity." },
  { id: "m11-46", m: 11, term: "Risk Sharing", vi: "Chia sẻ rủi ro: phân bổ quyền sở hữu một opportunity cho bên thứ ba có khả năng nắm bắt cơ hội đó tốt nhất (VD: liên doanh, hợp tác)." },
  { id: "m11-47", m: 11, term: "Emergent Risk", vi: "Rủi ro mới nổi: rủi ro phát sinh mà không thể được nhận diện từ trước, chỉ xuất hiện trong quá trình dự án diễn ra." },
  { id: "m11-48", m: 11, term: "Enterprise Risk Management (ERM)", vi: "Quản lý rủi ro doanh nghiệp: cách tiếp cận quản lý rủi ro phản ánh văn hóa, năng lực và chiến lược của cả tổ chức nhằm tạo và duy trì giá trị — ở cấp độ cao hơn quản lý rủi ro của một dự án đơn lẻ." },
  { id: "m11-49", m: 11, term: "Probability and Impact Matrix", vi: "Ma trận xác suất - tác động: lưới dùng để ánh xạ xác suất xảy ra của từng rủi ro với mức độ ảnh hưởng của nó lên mục tiêu dự án, làm công cụ trực quan cho Qualitative Risk Analysis." },

  // ===== MODULE 12: Procurement Management =====
  { id: "m12-01", m: 12, term: "Procurement", vi: "Mua sắm: quy trình thu mua sản phẩm, dịch vụ hoặc kết quả cần thiết từ bên ngoài đội dự án." },
  { id: "m12-02", m: 12, term: "Contract", vi: "Hợp đồng: thỏa thuận ràng buộc pháp lý giữa buyer và seller, buyer trả tiền để nhận sản phẩm/dịch vụ/kết quả." },
  { id: "m12-03", m: 12, term: "Fixed Price Contract (FP)", vi: "Hợp đồng giá cố định: giá đã thỏa thuận trước, rủi ro tăng chi phí thuộc về seller." },
  { id: "m12-04", m: 12, term: "Firm Fixed Price (FFP)", vi: "Giá cố định chắc chắn: seller chịu toàn bộ rủi ro nếu chi phí thực tế tăng." },
  { id: "m12-05", m: 12, term: "Fixed Price Incentive Fee (FPIF)", vi: "Giá cố định có thưởng: seller được thưởng thêm nếu đạt các mục tiêu hiệu suất (VD hoàn thành sớm)." },
  { id: "m12-06", m: 12, term: "Fixed Price Economic Price Adjustment (FPEPA)", vi: "Giá cố định có điều chỉnh kinh tế: cho phép điều chỉnh giá theo chỉ số kinh tế (lạm phát...) trong hợp đồng dài hạn." },
  { id: "m12-07", m: 12, term: "Cost Reimbursable Contract (CR)", vi: "Hợp đồng hoàn phí: buyer trả chi phí thực tế cộng thêm phí (fee), dùng khi phạm vi công việc chưa rõ ràng." },
  { id: "m12-08", m: 12, term: "Cost Plus Fixed Fee (CPFF)", vi: "Chi phí cộng phí cố định: seller được trả chi phí thực tế cộng một khoản phí cố định không đổi." },
  { id: "m12-09", m: 12, term: "Cost Plus Incentive Fee (CPIF)", vi: "Chi phí cộng phí khuyến khích: seller được thưởng thêm nếu đạt mục tiêu hiệu suất đã thỏa thuận." },
  { id: "m12-10", m: 12, term: "Cost Plus Award Fee (CPAF)", vi: "Chi phí cộng phí thưởng: phí thưởng do buyer quyết định chủ quan, thường không thể khiếu nại." },
  { id: "m12-11", m: 12, term: "Time & Material Contract (T&M)", vi: "Hợp đồng theo thời gian và vật liệu: hình thức lai giữa fixed-price và cost-reimbursable, dùng khi chưa xác định chính xác phạm vi công việc." },
  { id: "m12-12", m: 12, term: "Make-or-Buy Analysis", vi: "Phân tích tự làm hay mua ngoài: xác định một sản phẩm/dịch vụ nên được tự sản xuất nội bộ hay mua từ bên ngoài." },
  { id: "m12-13", m: 12, term: "Procurement Statement of Work (SOW)", vi: "Bản mô tả công việc mua sắm: mô tả chi tiết phần phạm vi dự án sẽ được đưa vào hợp đồng." },
  { id: "m12-14", m: 12, term: "Request for Information (RFI)", vi: "Yêu cầu cung cấp thông tin: dùng khi cần thêm thông tin về hàng hóa/dịch vụ từ seller." },
  { id: "m12-15", m: 12, term: "Request for Proposal (RFP)", vi: "Yêu cầu đề xuất: dùng khi năng lực kỹ thuật hoặc phương pháp tiếp cận là yếu tố quan trọng nhất." },
  { id: "m12-16", m: 12, term: "Request for Quotation (RFQ)", vi: "Yêu cầu báo giá: dùng khi quyết định chọn seller chủ yếu dựa trên giá." },
  { id: "m12-17", m: 12, term: "Invitation for Bid (IFB)", vi: "Thư mời thầu: lời mời nhà thầu/nhà cung cấp thiết bị nộp đề xuất." },
  { id: "m12-18", m: 12, term: "Non-Disclosure Agreement (NDA)", vi: "Thỏa thuận bảo mật: hợp đồng pháp lý xác lập quan hệ bảo mật thông tin giữa các bên." },
  { id: "m12-19", m: 12, term: "Letter of Intent (LOI)", vi: "Thư ý định: không phải hợp đồng, chỉ thể hiện ý định của buyer muốn thuê seller." },
  { id: "m12-20", m: 12, term: "Bidder Conference", vi: "Hội nghị nhà thầu: cuộc họp với các nhà cung cấp tiềm năng trước khi họ hoàn thành đề xuất, đảm bảo hiểu đúng và công bằng yêu cầu." },
  { id: "m12-21", m: 12, term: "Source Selection Criteria", vi: "Tiêu chí lựa chọn nhà cung cấp: hệ thống trọng số dùng để chọn seller và thiết lập thứ tự đàm phán." },
  { id: "m12-22", m: 12, term: "Centralized vs Decentralized Contracting", vi: "Tập trung (một phòng mua sắm quản lý tất cả hợp đồng) khác với phân tán (PM tự đàm phán và ký hợp đồng)." },
  { id: "m12-23", m: 12, term: "Claims Administration", vi: "Quản lý khiếu nại: xử lý các yêu cầu bồi thường khi seller cho rằng buyer đã gây thiệt hại cho họ." },
  { id: "m12-24", m: 12, term: "Alternative Dispute Resolution (ADR)", vi: "Giải quyết tranh chấp thay thế: hòa giải hoặc trọng tài, được ưu tiên trước khi đưa ra tòa án (litigation)." },
  { id: "m12-25", m: 12, term: "Procurement Audit", vi: "Đánh giá mua sắm: xem xét quy trình mua sắm để tìm điểm cần cải thiện và rút ra bài học kinh nghiệm." },
  { id: "m12-26", m: 12, term: "Master Service Agreement (MSA)", vi: "Thỏa thuận dịch vụ khung: hợp đồng tổng thể chi phối mối quan hệ dài hạn với seller, các công việc adaptive được đính kèm phụ lục riêng." },
  { id: "m12-27", m: 12, term: "Change for Free (Agile Contracting)", vi: "Điều khoản \"thay đổi miễn phí\": khách hàng có thể đổi tính năng mới lấy tính năng ưu tiên thấp hơn với cùng effort, miễn phí." },
  { id: "m12-28", m: 12, term: "Money for Nothing (Agile Contracting)", vi: "Điều khoản \"tiền không cho gì\": cho phép khách hàng chấm dứt hợp đồng sớm nếu thấy backlog còn lại không còn đáng giá." },
  { id: "m12-29", m: 12, term: "Graduated Fixed Price (Agile Contracting)", vi: "Giá cố định phân bậc: chia sẻ rủi ro/thưởng giữa hai bên dựa trên biến động tiến độ, với đơn giá khác nhau tùy giao hàng sớm/đúng hạn/trễ." },
  { id: "m12-30", m: 12, term: "Fixed Price Work Packages (Agile Contracting)", vi: "Giá cố định theo từng gói công việc nhỏ, giảm rủi ro ước lượng sai cho cả gói lớn." },
  { id: "m12-31", m: 12, term: "Point of Total Assumption (PTA)", vi: "Điểm giả định toàn phần: mức chi phí mà từ đó trở đi, seller trong hợp đồng FPIF phải tự chịu toàn bộ chi phí vượt trội, không còn được buyer chia sẻ. Công thức: PTA = [(Ceiling Price − Target Price) / Buyer's Share Ratio] + Target Cost." },
  { id: "m12-32", m: 12, term: "Warranty", vi: "Bảo hành: cam kết của seller về chất lượng/hiệu năng sản phẩm trong một khoảng thời gian nhất định sau khi bàn giao." },
  { id: "m12-33", m: 12, term: "Termination for Convenience / for Cause", vi: "Chấm dứt hợp đồng vì thuận tiện (buyer tự quyết, không cần lỗi từ seller) hoặc vì lý do vi phạm (seller không thực hiện đúng nghĩa vụ hợp đồng)." },
];

if (typeof module !== "undefined") {
  module.exports = { MODULES, VOCAB };
}
